# PyTorch Fundamentals

In [117]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


## Creating tensors

In [118]:
# scalar
scalar = torch.tensor(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
scalar.item()

In [ ]:
# vector
vector = torch.tensor([5, 6])
vector

tensor([5, 6])

In [ ]:
vector.ndim

1

In [ ]:
for item in vector:
    print(item.item())

5
6


In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
matrix = torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([4, 5, 6])

In [ ]:
matrix[:, 0]

tensor([1, 4, 7])

In [ ]:
matrix[:, :1]

tensor([[1],
        [4],
        [7]])

In [ ]:
matrix[:, :2]

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [ ]:
# tensor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [5,4,3]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [5, 4, 3]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [5, 4, 3]])

In [ ]:
tensor[0][1]

tensor([4, 5, 6])

### Random tensors

In [ ]:
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[3.4217e-02, 5.5598e-01, 1.9535e-01],
         [7.4215e-01, 6.4372e-01, 2.2162e-01],
         [2.6883e-01, 5.1484e-01, 7.0911e-01],
         [9.7576e-01, 1.8803e-01, 8.8962e-01]],

        [[8.7671e-01, 7.1626e-01, 9.3397e-01],
         [2.0856e-01, 8.3768e-01, 1.1527e-01],
         [2.1115e-01, 2.7373e-01, 2.5367e-03],
         [4.2294e-01, 5.7125e-04, 7.7881e-01]],

        [[6.6577e-02, 5.1834e-01, 7.6489e-01],
         [6.8273e-01, 8.8941e-01, 5.9535e-01],
         [9.0007e-01, 3.5507e-01, 5.2702e-01],
         [9.1345e-01, 7.7352e-01, 4.5545e-01]]])

In [ ]:
random_image_tensor = torch.rand(size=(224,224,3)) # dimension and color channels
random_image_tensor.ndim, random_image_tensor.size()

(3, torch.Size([224, 224, 3]))

### Zeros and ones

In [138]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [139]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [140]:
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

### Range and like

In [141]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
torch.zeros_like(torch.zeros(1, 11))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [143]:
torch.zeros_like(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Data Type

In [144]:
float_32_tensor = torch.tensor([3.0,4,5],
                               dtype=None, # "float32", "float16"
                               device=None, # "cpu", "cuda"
                               requires_grad=False)
float_32_tensor

tensor([3., 4., 5.])

In [145]:
float_32_tensor.dtype

torch.float32

In [146]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [147]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 25.])