# PyTorch Fundamentals

In [150]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


## Creating tensors

In [151]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [152]:
scalar.ndim

0

In [153]:
scalar.item()

7

In [154]:
# vector
vector = torch.tensor([5, 6])
vector

tensor([5, 6])

In [155]:
vector.ndim

1

In [156]:
for item in vector:
    print(item.item())

5
6


In [157]:
vector.shape

torch.Size([2])

In [158]:
# matrix
matrix = torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [159]:
matrix.ndim

2

In [160]:
matrix[1]

tensor([4, 5, 6])

In [161]:
matrix[:, 0]

tensor([1, 4, 7])

In [162]:
matrix[:, :1]

tensor([[1],
        [4],
        [7]])

In [163]:
matrix[:, :2]

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [164]:
# tensor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [5,4,3]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [5, 4, 3]]])

In [165]:
tensor.ndim

3

In [166]:
tensor.shape

torch.Size([1, 3, 3])

In [167]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [5, 4, 3]])

In [168]:
tensor[0][1]

tensor([4, 5, 6])

### Random tensors

In [169]:
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.7428, 0.2457, 0.4204],
         [0.7446, 0.1863, 0.5550],
         [0.6280, 0.9950, 0.3926],
         [0.8035, 0.7935, 0.3221]],

        [[0.1593, 0.7354, 0.2283],
         [0.3126, 0.5114, 0.6756],
         [0.8628, 0.2189, 0.9314],
         [0.0018, 0.8631, 0.1004]],

        [[0.2517, 0.7197, 0.1890],
         [0.0164, 0.1542, 0.6545],
         [0.3649, 0.1567, 0.2555],
         [0.9201, 0.2020, 0.3858]]])

In [170]:
random_image_tensor = torch.rand(size=(224,224,3)) # dimension and color channels
random_image_tensor.ndim, random_image_tensor.size()

(3, torch.Size([224, 224, 3]))

### Zeros and ones

In [171]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [172]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [173]:
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

### Range and like

In [174]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
torch.zeros_like(torch.zeros(1, 11))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [176]:
torch.zeros_like(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Data Type

In [177]:
float_32_tensor = torch.tensor([3.0,4,5],
                               dtype=None, # "float32", "float16"
                               device=None, # "cpu", "cuda"
                               requires_grad=False)
float_32_tensor

tensor([3., 4., 5.])

In [178]:
float_32_tensor.dtype

torch.float32

In [179]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [180]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 25.])

In [181]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [182]:
int_32_tensor / float_32_tensor

tensor([1., 1., 1.])

### Getting Tensor Information

In [185]:
int_32_tensor.dtype, int_32_tensor.shape, int_32_tensor.device

(torch.int32, torch.Size([3]), device(type='cpu'))

In [186]:
int_32_tensor.size()

torch.Size([3])