# Operations

- Addition
- Subtraction
- Element-wise Multiplication
- Division
- Matrix Multiplication

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


In [3]:
tensor = torch.rand(size=(3,4,5))
tensor

tensor([[[0.2818, 0.1495, 0.5517, 0.5402, 0.7517],
         [0.6338, 0.3160, 0.9374, 0.1699, 0.5597],
         [0.2821, 0.1154, 0.1507, 0.3532, 0.7151],
         [0.2274, 0.1539, 0.4514, 0.0427, 0.0183]],

        [[0.5463, 0.9786, 0.4834, 0.0113, 0.4004],
         [0.2662, 0.8555, 0.0201, 0.7162, 0.6784],
         [0.4875, 0.1879, 0.2830, 0.0108, 0.8607],
         [0.1719, 0.1460, 0.6601, 0.2030, 0.0802]],

        [[0.5703, 0.1553, 0.1959, 0.5292, 0.9920],
         [0.8247, 0.7057, 0.9439, 0.1518, 0.9944],
         [0.4888, 0.4425, 0.4058, 0.3256, 0.9304],
         [0.0789, 0.8259, 0.3209, 0.1082, 0.9269]]])

In [4]:
tensor * 100

tensor([[[28.1808, 14.9467, 55.1660, 54.0202, 75.1680],
         [63.3847, 31.5961, 93.7363, 16.9909, 55.9736],
         [28.2126, 11.5416, 15.0730, 35.3235, 71.5148],
         [22.7366, 15.3936, 45.1448,  4.2681,  1.8292]],

        [[54.6286, 97.8624, 48.3448,  1.1279, 40.0354],
         [26.6205, 85.5493,  2.0102, 71.6158, 67.8411],
         [48.7492, 18.7912, 28.3002,  1.0756, 86.0687],
         [17.1928, 14.5994, 66.0090, 20.2976,  8.0246]],

        [[57.0297, 15.5324, 19.5921, 52.9175, 99.2014],
         [82.4737, 70.5730, 94.3929, 15.1798, 99.4351],
         [48.8771, 44.2503, 40.5807, 32.5571, 93.0442],
         [ 7.8883, 82.5874, 32.0938, 10.8233, 92.6937]]])

In [5]:
tensor * tensor

tensor([[[7.9416e-02, 2.2340e-02, 3.0433e-01, 2.9182e-01, 5.6502e-01],
         [4.0176e-01, 9.9832e-02, 8.7865e-01, 2.8869e-02, 3.1330e-01],
         [7.9595e-02, 1.3321e-02, 2.2719e-02, 1.2478e-01, 5.1144e-01],
         [5.1695e-02, 2.3696e-02, 2.0381e-01, 1.8217e-03, 3.3461e-04]],

        [[2.9843e-01, 9.5771e-01, 2.3372e-01, 1.2721e-04, 1.6028e-01],
         [7.0865e-02, 7.3187e-01, 4.0410e-04, 5.1288e-01, 4.6024e-01],
         [2.3765e-01, 3.5311e-02, 8.0090e-02, 1.1569e-04, 7.4078e-01],
         [2.9559e-02, 2.1314e-02, 4.3572e-01, 4.1199e-02, 6.4394e-03]],

        [[3.2524e-01, 2.4125e-02, 3.8385e-02, 2.8003e-01, 9.8409e-01],
         [6.8019e-01, 4.9805e-01, 8.9100e-01, 2.3043e-02, 9.8873e-01],
         [2.3890e-01, 1.9581e-01, 1.6468e-01, 1.0600e-01, 8.6572e-01],
         [6.2225e-03, 6.8207e-01, 1.0300e-01, 1.1714e-02, 8.5921e-01]]])

In [6]:
tensor - 1

tensor([[[-0.7182, -0.8505, -0.4483, -0.4598, -0.2483],
         [-0.3662, -0.6840, -0.0626, -0.8301, -0.4403],
         [-0.7179, -0.8846, -0.8493, -0.6468, -0.2849],
         [-0.7726, -0.8461, -0.5486, -0.9573, -0.9817]],

        [[-0.4537, -0.0214, -0.5166, -0.9887, -0.5996],
         [-0.7338, -0.1445, -0.9799, -0.2838, -0.3216],
         [-0.5125, -0.8121, -0.7170, -0.9892, -0.1393],
         [-0.8281, -0.8540, -0.3399, -0.7970, -0.9198]],

        [[-0.4297, -0.8447, -0.8041, -0.4708, -0.0080],
         [-0.1753, -0.2943, -0.0561, -0.8482, -0.0056],
         [-0.5112, -0.5575, -0.5942, -0.6744, -0.0696],
         [-0.9211, -0.1741, -0.6791, -0.8918, -0.0731]]])

In [7]:
tensor.mul(10)

tensor([[[2.8181, 1.4947, 5.5166, 5.4020, 7.5168],
         [6.3385, 3.1596, 9.3736, 1.6991, 5.5974],
         [2.8213, 1.1542, 1.5073, 3.5324, 7.1515],
         [2.2737, 1.5394, 4.5145, 0.4268, 0.1829]],

        [[5.4629, 9.7862, 4.8345, 0.1128, 4.0035],
         [2.6620, 8.5549, 0.2010, 7.1616, 6.7841],
         [4.8749, 1.8791, 2.8300, 0.1076, 8.6069],
         [1.7193, 1.4599, 6.6009, 2.0298, 0.8025]],

        [[5.7030, 1.5532, 1.9592, 5.2918, 9.9201],
         [8.2474, 7.0573, 9.4393, 1.5180, 9.9435],
         [4.8877, 4.4250, 4.0581, 3.2557, 9.3044],
         [0.7888, 8.2587, 3.2094, 1.0823, 9.2694]]])

In [8]:
torch.mul(tensor, 10)

tensor([[[2.8181, 1.4947, 5.5166, 5.4020, 7.5168],
         [6.3385, 3.1596, 9.3736, 1.6991, 5.5974],
         [2.8213, 1.1542, 1.5073, 3.5324, 7.1515],
         [2.2737, 1.5394, 4.5145, 0.4268, 0.1829]],

        [[5.4629, 9.7862, 4.8345, 0.1128, 4.0035],
         [2.6620, 8.5549, 0.2010, 7.1616, 6.7841],
         [4.8749, 1.8791, 2.8300, 0.1076, 8.6069],
         [1.7193, 1.4599, 6.6009, 2.0298, 0.8025]],

        [[5.7030, 1.5532, 1.9592, 5.2918, 9.9201],
         [8.2474, 7.0573, 9.4393, 1.5180, 9.9435],
         [4.8877, 4.4250, 4.0581, 3.2557, 9.3044],
         [0.7888, 8.2587, 3.2094, 1.0823, 9.2694]]])

## Matrix Multiplication

In [9]:
matrix1 = torch.rand(size=(3,3))
matrix2 = torch.rand(size=(3,3))
matrix1, matrix2

(tensor([[0.3731, 0.8996, 0.6252],
         [0.0028, 0.4122, 0.9866],
         [0.7737, 0.7632, 0.6103]]),
 tensor([[0.0181, 0.3081, 0.6245],
         [0.8243, 0.7089, 0.9967],
         [0.5885, 0.7293, 0.9370]]))

In [10]:
torch.matmul(matrix1, matrix2)

tensor([[1.1161, 1.2086, 1.7154],
        [0.9204, 1.0126, 1.3371],
        [1.0023, 1.2246, 1.8158]])

In [11]:
torch.matmul(matrix2, matrix1)

tensor([[0.4908, 0.6199, 0.6964],
        [1.0807, 1.7944, 1.8231],
        [0.9466, 1.5451, 1.6593]])

In [12]:
three_by_two_mat = matrix1[:, :2]
three_by_two_mat

tensor([[0.3731, 0.8996],
        [0.0028, 0.4122],
        [0.7737, 0.7632]])

In [13]:
torch.mm(three_by_two_mat, three_by_two_mat.T)

tensor([[0.9484, 0.3718, 0.9753],
        [0.3718, 0.1699, 0.3168],
        [0.9753, 0.3168, 1.1812]])

In [14]:
torch.mm(three_by_two_mat.T, three_by_two_mat)

tensor([[0.7379, 0.9273],
        [0.9273, 1.5616]])

In [15]:
three_by_two_mat.shape

torch.Size([3, 2])

In [16]:
three_by_two_mat.T.shape

torch.Size([2, 3])

In [17]:
three_by_two_mat.T.T.T.T.T

tensor([[0.3731, 0.0028, 0.7737],
        [0.8996, 0.4122, 0.7632]])

In [18]:
torch.min(three_by_two_mat)

tensor(0.0028)

In [19]:
torch.max(three_by_two_mat)

tensor(0.8996)

In [20]:
torch.mean(three_by_two_mat)

tensor(0.5374)

In [21]:
three_by_two_mat.sum()

tensor(3.2247)

In [22]:
three_by_two_mat

tensor([[0.3731, 0.8996],
        [0.0028, 0.4122],
        [0.7737, 0.7632]])

In [23]:
three_by_two_mat.argmin() # index in which the min is

tensor(2)

In [24]:
three_by_two_mat.argmax()

tensor(1)

- reshape
- view
- stacking
- squeeze
- unsqueeze
- permute

In [25]:
three_by_two_mat

tensor([[0.3731, 0.8996],
        [0.0028, 0.4122],
        [0.7737, 0.7632]])

In [26]:
three_by_two_mat.reshape(2, 3) # not a transpose

tensor([[0.3731, 0.8996, 0.0028],
        [0.4122, 0.7737, 0.7632]])

In [27]:
three_by_two_mat.reshape(1, 6)

tensor([[0.3731, 0.8996, 0.0028, 0.4122, 0.7737, 0.7632]])

In [28]:
view = three_by_two_mat.view(3, 2)
view

tensor([[0.3731, 0.8996],
        [0.0028, 0.4122],
        [0.7737, 0.7632]])

In [29]:
view[0][0] = 0
view

tensor([[0.0000, 0.8996],
        [0.0028, 0.4122],
        [0.7737, 0.7632]])

In [30]:
three_by_two_mat # with a view, the original tensor is updated

tensor([[0.0000, 0.8996],
        [0.0028, 0.4122],
        [0.7737, 0.7632]])

In [31]:
torch.stack([three_by_two_mat, three_by_two_mat], dim=1)

tensor([[[0.0000, 0.8996],
         [0.0000, 0.8996]],

        [[0.0028, 0.4122],
         [0.0028, 0.4122]],

        [[0.7737, 0.7632],
         [0.7737, 0.7632]]])

In [32]:
three_by_two_mat

tensor([[0.0000, 0.8996],
        [0.0028, 0.4122],
        [0.7737, 0.7632]])

In [33]:
three_by_two_mat.squeeze()

tensor([[0.0000, 0.8996],
        [0.0028, 0.4122],
        [0.7737, 0.7632]])

In [34]:
one_more_dim = three_by_two_mat.reshape(1, 2, 3)
one_more_dim

tensor([[[0.0000, 0.8996, 0.0028],
         [0.4122, 0.7737, 0.7632]]])

In [35]:
one_more_dim.squeeze()

tensor([[0.0000, 0.8996, 0.0028],
        [0.4122, 0.7737, 0.7632]])

In [36]:
two_more_dim = three_by_two_mat.reshape(1, 1, 2, 3)
two_more_dim

tensor([[[[0.0000, 0.8996, 0.0028],
          [0.4122, 0.7737, 0.7632]]]])

In [37]:
two_more_dim.squeeze()

tensor([[0.0000, 0.8996, 0.0028],
        [0.4122, 0.7737, 0.7632]])