# Operations

- Addition
- Subtraction
- Element-wise Multiplication
- Division
- Matrix Multiplication

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


In [4]:
tensor = torch.rand(size=(3,4,5))
tensor

tensor([[[0.3558, 0.1775, 0.8110, 0.9356, 0.7801],
         [0.4146, 0.4993, 0.1294, 0.7811, 0.0459],
         [0.1024, 0.8436, 0.9769, 0.2030, 0.2200],
         [0.4412, 0.8271, 0.6806, 0.0731, 0.7362]],

        [[0.8359, 0.1613, 0.6560, 0.6826, 0.3888],
         [0.9157, 0.1422, 0.2341, 0.2477, 0.2091],
         [0.5491, 0.4770, 0.4849, 0.7461, 0.8457],
         [0.3041, 0.6404, 0.6863, 0.5203, 0.9443]],

        [[0.2502, 0.6990, 0.0035, 0.2984, 0.4060],
         [0.0477, 0.8848, 0.3617, 0.4971, 0.9303],
         [0.9958, 0.2873, 0.3423, 0.5845, 0.8459],
         [0.8508, 0.4319, 0.8752, 0.6074, 0.6130]]])

In [5]:
tensor * 100

tensor([[[35.5800, 17.7512, 81.1012, 93.5644, 78.0080],
         [41.4626, 49.9344, 12.9411, 78.1144,  4.5870],
         [10.2423, 84.3629, 97.6887, 20.3050, 22.0006],
         [44.1183, 82.7086, 68.0624,  7.3060, 73.6208]],

        [[83.5902, 16.1323, 65.5981, 68.2611, 38.8825],
         [91.5654, 14.2179, 23.4130, 24.7709, 20.9055],
         [54.9094, 47.7008, 48.4872, 74.6073, 84.5737],
         [30.4137, 64.0367, 68.6312, 52.0301, 94.4330]],

        [[25.0187, 69.9021,  0.3507, 29.8418, 40.6001],
         [ 4.7720, 88.4822, 36.1675, 49.7138, 93.0304],
         [99.5845, 28.7341, 34.2266, 58.4529, 84.5891],
         [85.0829, 43.1904, 87.5193, 60.7385, 61.2973]]])

In [6]:
tensor * tensor

tensor([[[1.2659e-01, 3.1510e-02, 6.5774e-01, 8.7543e-01, 6.0853e-01],
         [1.7192e-01, 2.4934e-01, 1.6747e-02, 6.1019e-01, 2.1041e-03],
         [1.0491e-02, 7.1171e-01, 9.5431e-01, 4.1229e-02, 4.8403e-02],
         [1.9464e-01, 6.8407e-01, 4.6325e-01, 5.3378e-03, 5.4200e-01]],

        [[6.9873e-01, 2.6025e-02, 4.3031e-01, 4.6596e-01, 1.5118e-01],
         [8.3842e-01, 2.0215e-02, 5.4817e-02, 6.1360e-02, 4.3704e-02],
         [3.0150e-01, 2.2754e-01, 2.3510e-01, 5.5663e-01, 7.1527e-01],
         [9.2499e-02, 4.1007e-01, 4.7102e-01, 2.7071e-01, 8.9176e-01]],

        [[6.2594e-02, 4.8863e-01, 1.2296e-05, 8.9053e-02, 1.6484e-01],
         [2.2772e-03, 7.8291e-01, 1.3081e-01, 2.4715e-01, 8.6547e-01],
         [9.9171e-01, 8.2565e-02, 1.1715e-01, 3.4167e-01, 7.1553e-01],
         [7.2391e-01, 1.8654e-01, 7.6596e-01, 3.6892e-01, 3.7574e-01]]])

In [7]:
tensor - 1

tensor([[[-0.6442, -0.8225, -0.1890, -0.0644, -0.2199],
         [-0.5854, -0.5007, -0.8706, -0.2189, -0.9541],
         [-0.8976, -0.1564, -0.0231, -0.7970, -0.7800],
         [-0.5588, -0.1729, -0.3194, -0.9269, -0.2638]],

        [[-0.1641, -0.8387, -0.3440, -0.3174, -0.6112],
         [-0.0843, -0.8578, -0.7659, -0.7523, -0.7909],
         [-0.4509, -0.5230, -0.5151, -0.2539, -0.1543],
         [-0.6959, -0.3596, -0.3137, -0.4797, -0.0557]],

        [[-0.7498, -0.3010, -0.9965, -0.7016, -0.5940],
         [-0.9523, -0.1152, -0.6383, -0.5029, -0.0697],
         [-0.0042, -0.7127, -0.6577, -0.4155, -0.1541],
         [-0.1492, -0.5681, -0.1248, -0.3926, -0.3870]]])

In [8]:
tensor.mul(10)

tensor([[[3.5580, 1.7751, 8.1101, 9.3564, 7.8008],
         [4.1463, 4.9934, 1.2941, 7.8114, 0.4587],
         [1.0242, 8.4363, 9.7689, 2.0305, 2.2001],
         [4.4118, 8.2709, 6.8062, 0.7306, 7.3621]],

        [[8.3590, 1.6132, 6.5598, 6.8261, 3.8883],
         [9.1565, 1.4218, 2.3413, 2.4771, 2.0906],
         [5.4909, 4.7701, 4.8487, 7.4607, 8.4574],
         [3.0414, 6.4037, 6.8631, 5.2030, 9.4433]],

        [[2.5019, 6.9902, 0.0351, 2.9842, 4.0600],
         [0.4772, 8.8482, 3.6167, 4.9714, 9.3030],
         [9.9584, 2.8734, 3.4227, 5.8453, 8.4589],
         [8.5083, 4.3190, 8.7519, 6.0739, 6.1297]]])

In [9]:
torch.mul(tensor, 10)

tensor([[[3.5580, 1.7751, 8.1101, 9.3564, 7.8008],
         [4.1463, 4.9934, 1.2941, 7.8114, 0.4587],
         [1.0242, 8.4363, 9.7689, 2.0305, 2.2001],
         [4.4118, 8.2709, 6.8062, 0.7306, 7.3621]],

        [[8.3590, 1.6132, 6.5598, 6.8261, 3.8883],
         [9.1565, 1.4218, 2.3413, 2.4771, 2.0906],
         [5.4909, 4.7701, 4.8487, 7.4607, 8.4574],
         [3.0414, 6.4037, 6.8631, 5.2030, 9.4433]],

        [[2.5019, 6.9902, 0.0351, 2.9842, 4.0600],
         [0.4772, 8.8482, 3.6167, 4.9714, 9.3030],
         [9.9584, 2.8734, 3.4227, 5.8453, 8.4589],
         [8.5083, 4.3190, 8.7519, 6.0739, 6.1297]]])

## Matrix Multiplication

In [14]:
matrix1 = torch.rand(size=(3,3))
matrix2 = torch.rand(size=(3,3))
matrix1, matrix2

(tensor([[0.9794, 0.4698, 0.2823],
         [0.7693, 0.1070, 0.9812],
         [0.4702, 0.6696, 0.7954]]),
 tensor([[0.4387, 0.2362, 0.5653],
         [0.4518, 0.9419, 0.3153],
         [0.0279, 0.2340, 0.9786]]))

In [15]:
torch.matmul(matrix1, matrix2)

tensor([[0.6498, 0.7399, 0.9780],
        [0.4132, 0.5121, 1.4288],
        [0.5310, 0.9279, 1.2553]])

In [16]:
torch.matmul(matrix2, matrix1)

tensor([[0.8772, 0.6099, 0.8052],
        [1.3153, 0.5242, 1.3026],
        [0.6675, 0.6934, 1.0158]])

In [24]:
three_by_two_mat = matrix1[:, :2]
three_by_two_mat

tensor([[0.9794, 0.4698],
        [0.7693, 0.1070],
        [0.4702, 0.6696]])

In [25]:
torch.mm(three_by_two_mat, three_by_two_mat.T)

tensor([[1.1799, 0.8037, 0.7751],
        [0.8037, 0.6033, 0.4334],
        [0.7751, 0.4334, 0.6696]])

In [26]:
torch.mm(three_by_two_mat.T, three_by_two_mat)

tensor([[1.7721, 0.8573],
        [0.8573, 0.6806]])

In [27]:
three_by_two_mat.shape

torch.Size([3, 2])

In [28]:
three_by_two_mat.T.shape

torch.Size([2, 3])

In [29]:
three_by_two_mat.T.T.T.T.T

tensor([[0.9794, 0.7693, 0.4702],
        [0.4698, 0.1070, 0.6696]])